export const AUTH_ACCESS_TOKEN_COOKIE_NAME = "artmate_access_token";
export const AUTH_OAUTH_STATE_COOKIE_PREFIX = "artmate_oauth_state";

export const AUTH_ACCESS_TOKEN_EXPIRES_IN = "7d";
export const AUTH_ACCESS_TOKEN_MAX_AGE_MS = 1000 * 60 * 60 * 24 * 7;
export const AUTH_OAUTH_STATE_MAX_AGE_MS = 1000 * 60 * 10;
export const AUTH_LOGIN_THROTTLE_WINDOW_MS = 1000 * 60 * 15;
export const AUTH_LOGIN_LOCKOUT_MS = 1000 * 60 * 15;
export const AUTH_LOGIN_MAX_FAILED_ATTEMPTS = 5;
export const AUTH_LOGIN_IP_MAX_FAILED_ATTEMPTS = 20;
export const AUTH_EMAIL_VERIFICATION_DEFAULT_CODE_TTL_SECONDS = 60 * 10;
export const AUTH_EMAIL_VERIFICATION_DEFAULT_RESEND_COOLDOWN_SECONDS = 60;
export const AUTH_EMAIL_VERIFICATION_DEFAULT_MAX_ATTEMPTS = 5;
export const AUTH_EMAIL_VERIFICATION_DEFAULT_MAX_SENDS_PER_HOUR = 5;
export const AUTH_EMAIL_VERIFICATION_DEFAULT_IP_MAX_SENDS_PER_HOUR = 20;
export const AUTH_PASSWORD_RESET_DEFAULT_TOKEN_TTL_SECONDS = 60 * 30;
export const AUTH_PASSWORD_RESET_DEFAULT_RESEND_COOLDOWN_SECONDS = 60;
export const AUTH_PASSWORD_RESET_DEFAULT_MAX_SENDS_PER_HOUR = 5;
export const AUTH_PASSWORD_RESET_DEFAULT_IP_MAX_SENDS_PER_HOUR = 20;

export const YANDEX_AUTHORIZE_URL = "https://oauth.yandex.ru/authorize";
export const YANDEX_TOKEN_URL = "https://oauth.yandex.ru/token";
export const YANDEX_PROFILE_URL = "https://login.yandex.ru/info?format=json";
