export const CONTACT_MESSAGE_NAME_MAX_LENGTH = 80;
export const CONTACT_MESSAGE_EMAIL_MAX_LENGTH = 254;
export const CONTACT_MESSAGE_TOPIC_MAX_LENGTH = 80;
export const CONTACT_MESSAGE_ORDER_MAX_LENGTH = 80;
export const CONTACT_MESSAGE_TEXT_MAX_LENGTH = 2000;
