export type OzonMockPickupPoint = {
  mapPointId: number;
  externalId: string;
  city: "Москва" | "Санкт-Петербург";
  name: string;
  address: string;
  lat: number;
  long: number;
  type: "PVZ" | "POSTAMAT";
  status: "available" | "temporarily_unavailable";
  workHours: string;
  deliveryPrice: number;
  deliveryTermDays: number;
  maxWeightGrams: number;
  maxDimensionsCm: {
    width: number;
    height: number;
    depth: number;
  };
  availableDeliveryMethods: string[];
  paymentMethods: string[];
  restrictions: string[];
  howToGet: string;
};

export const OZON_MOCK_PICKUP_POINTS: OzonMockPickupPoint[] = [
  {
    mapPointId: 100101,
    externalId: "ozon-tverskaya-12",
    city: "Москва",
    name: "Ozon ПВЗ, Тверская",
    address: "Москва, ул. Тверская, 12с1",
    lat: 55.762147,
    long: 37.608103,
    type: "PVZ",
    status: "available",
    workHours: "Ежедневно 09:00-22:00",
    deliveryPrice: 350,
    deliveryTermDays: 2,
    maxWeightGrams: 15000,
    maxDimensionsCm: {
      width: 60,
      height: 60,
      depth: 80,
    },
    availableDeliveryMethods: ["pickup", "partial_return"],
    paymentMethods: ["online_card"],
    restrictions: ["Проверка заказа при получении", "Возврат частями доступен"],
    howToGet: "Вход со стороны Тверской улицы, ПВЗ на первом этаже.",
  },
  {
    mapPointId: 100102,
    externalId: "ozon-pyatnitskaya-8",
    city: "Москва",
    name: "Ozon ПВЗ, Пятницкая",
    address: "Москва, ул. Пятницкая, 8",
    lat: 55.743742,
    long: 37.626257,
    type: "PVZ",
    status: "available",
    workHours: "Ежедневно 10:00-21:00",
    deliveryPrice: 350,
    deliveryTermDays: 2,
    maxWeightGrams: 12000,
    maxDimensionsCm: {
      width: 50,
      height: 50,
      depth: 70,
    },
    availableDeliveryMethods: ["pickup", "fitting_room"],
    paymentMethods: ["online_card"],
    restrictions: ["Без примерки для печатной продукции"],
    howToGet: "От метро Новокузнецкая 3 минуты пешком, вход рядом с аптекой.",
  },
  {
    mapPointId: 100103,
    externalId: "ozon-leningradskiy-31",
    city: "Москва",
    name: "Ozon ПВЗ, Ленинградский проспект",
    address: "Москва, Ленинградский проспект, 31А",
    lat: 55.78754,
    long: 37.565312,
    type: "PVZ",
    status: "available",
    workHours: "Пн-Сб 09:00-21:00, Вс 10:00-20:00",
    deliveryPrice: 390,
    deliveryTermDays: 2,
    maxWeightGrams: 20000,
    maxDimensionsCm: {
      width: 80,
      height: 60,
      depth: 80,
    },
    availableDeliveryMethods: ["pickup", "partial_return"],
    paymentMethods: ["online_card"],
    restrictions: ["Хранение заказа 7 дней"],
    howToGet: "ПВЗ расположен в торговой галерее, вход с Ленинградского проспекта.",
  },
  {
    mapPointId: 100104,
    externalId: "ozon-nikolskaya-10",
    city: "Москва",
    name: "Ozon ПВЗ, Никольская",
    address: "Москва, ул. Никольская, 10",
    lat: 55.756406,
    long: 37.621688,
    type: "PVZ",
    status: "available",
    workHours: "Ежедневно 09:00-23:00",
    deliveryPrice: 420,
    deliveryTermDays: 1,
    maxWeightGrams: 10000,
    maxDimensionsCm: {
      width: 50,
      height: 50,
      depth: 60,
    },
    availableDeliveryMethods: ["pickup"],
    paymentMethods: ["online_card"],
    restrictions: ["Высокая загрузка в вечернее время"],
    howToGet: "Вход через арку, далее направо к зоне выдачи.",
  },
  {
    mapPointId: 100105,
    externalId: "ozon-presnenskaya-12",
    city: "Москва",
    name: "Ozon ПВЗ, Пресненская набережная",
    address: "Москва, Пресненская наб., 12",
    lat: 55.749712,
    long: 37.539721,
    type: "POSTAMAT",
    status: "temporarily_unavailable",
    workHours: "Ежедневно 08:00-23:00",
    deliveryPrice: 450,
    deliveryTermDays: 3,
    maxWeightGrams: 5000,
    maxDimensionsCm: {
      width: 40,
      height: 40,
      depth: 60,
    },
    availableDeliveryMethods: ["postamat"],
    paymentMethods: ["online_card"],
    restrictions: ["Временно недоступен из-за обслуживания постамата"],
    howToGet: "Постамат в зоне ресепшен бизнес-центра.",
  },
  {
    mapPointId: 200201,
    externalId: "ozon-nevskiy-28",
    city: "Санкт-Петербург",
    name: "Ozon ПВЗ, Невский проспект",
    address: "Санкт-Петербург, Невский проспект, 28",
    lat: 59.934817,
    long: 30.333164,
    type: "PVZ",
    status: "available",
    workHours: "Ежедневно 09:00-22:00",
    deliveryPrice: 390,
    deliveryTermDays: 3,
    maxWeightGrams: 15000,
    maxDimensionsCm: {
      width: 60,
      height: 60,
      depth: 80,
    },
    availableDeliveryMethods: ["pickup", "partial_return"],
    paymentMethods: ["online_card"],
    restrictions: ["Хранение заказа 7 дней"],
    howToGet: "Вход с Невского проспекта, ПВЗ находится за кассами.",
  },
  {
    mapPointId: 200202,
    externalId: "ozon-ligovskiy-43",
    city: "Санкт-Петербург",
    name: "Ozon ПВЗ, Лиговский",
    address: "Санкт-Петербург, Лиговский проспект, 43-45",
    lat: 59.927013,
    long: 30.356486,
    type: "PVZ",
    status: "available",
    workHours: "Пн-Сб 10:00-21:00, Вс 10:00-20:00",
    deliveryPrice: 390,
    deliveryTermDays: 3,
    maxWeightGrams: 12000,
    maxDimensionsCm: {
      width: 50,
      height: 50,
      depth: 70,
    },
    availableDeliveryMethods: ["pickup"],
    paymentMethods: ["online_card"],
    restrictions: ["Без примерки для печатной продукции"],
    howToGet: "От метро Площадь Восстания 5 минут пешком, вход с проспекта.",
  },
  {
    mapPointId: 200203,
    externalId: "ozon-bolshoy-ps-74",
    city: "Санкт-Петербург",
    name: "Ozon ПВЗ, Большой проспект П.С.",
    address: "Санкт-Петербург, Большой проспект П.С., 74",
    lat: 59.965421,
    long: 30.311032,
    type: "PVZ",
    status: "available",
    workHours: "Ежедневно 09:00-21:00",
    deliveryPrice: 430,
    deliveryTermDays: 3,
    maxWeightGrams: 20000,
    maxDimensionsCm: {
      width: 70,
      height: 60,
      depth: 80,
    },
    availableDeliveryMethods: ["pickup", "partial_return"],
    paymentMethods: ["online_card"],
    restrictions: ["Хранение заказа 5 дней"],
    howToGet: "ПВЗ на первом этаже жилого дома, вход рядом с кофейней.",
  },
  {
    mapPointId: 200204,
    externalId: "ozon-vasilevskiy-6",
    city: "Санкт-Петербург",
    name: "Ozon Постамат, 6-я линия В.О.",
    address: "Санкт-Петербург, 6-я линия В.О., 29",
    lat: 59.940612,
    long: 30.278814,
    type: "POSTAMAT",
    status: "available",
    workHours: "Ежедневно 08:00-23:00",
    deliveryPrice: 450,
    deliveryTermDays: 4,
    maxWeightGrams: 5000,
    maxDimensionsCm: {
      width: 40,
      height: 40,
      depth: 60,
    },
    availableDeliveryMethods: ["postamat"],
    paymentMethods: ["online_card"],
    restrictions: ["Максимальный срок хранения 3 дня"],
    howToGet: "Постамат находится у входа в супермаркет.",
  },
];
