export const routes = {
  blog: "/blog",
  blogAuthors: "/blog/authors",
  blogCategories: "/blog/categories",
  blogPost: (postId: string) => `/blog/${postId}`,
  blogPosts: "/blog/posts",
  blogTags: "/blog/tags",
  catalogLandings: "/catalog-landings",
  catalogLanding: (landingId: string) => `/catalog-landings/${landingId}`,
  catalogLandingCreate: "/catalog-landings/new",
  digitalVersion: (collectionId: string) => `/digital-versions/${collectionId}`,
  digitalVersionColoring: (collectionId: string, coloringId: string) =>
    `/digital-versions/${collectionId}/colorings/${coloringId}`,
  digitalVersionCreate: "/digital-versions/new",
  digitalVersions: "/digital-versions",
  featureBanners: "/feature-banners",
  home: "/",
  login: "/login",
  mailings: "/mailings",
  order: (orderId: string) => `/orders/${orderId}`,
  orders: "/orders",
  product: (productId: string) => `/products/${productId}`,
  productCategories: "/products/categories",
  productTags: "/products/tags",
  products: "/products",
  promoCode: (promoCodeId: string) => `/promocodes/${promoCodeId}`,
  promoCodeCreate: "/promocodes/new",
  promoCodes: "/promocodes",
  seo: "/seo",
  users: "/users",
} as const;
