export const routes = {
  blog: "/blog",
  blogAuthors: "/blog/authors",
  blogCategories: "/blog/categories",
  blogPost: (postId: string) => `/blog/${postId}`,
  blogPosts: "/blog/posts",
  blogTags: "/blog/tags",
  featureBanners: "/feature-banners",
  home: "/",
  login: "/login",
  mailings: "/mailings",
  order: (orderId: string) => `/orders/${orderId}`,
  orders: "/orders",
  product: (productId: string) => `/products/${productId}`,
  productCategories: "/products/categories",
  products: "/products",
  seo: "/seo",
  users: "/users",
} as const;
