export { BlogPage } from "./blog";
export { metadata as blogMetadata } from "./blog/metadata";
export { BlogPostPage } from "./blog-post";
export { CatalogPage } from "./catalog";
export { metadata as catalogMetadata } from "./catalog/metadata";
export { ContactsPage } from "./contacts";
export { metadata as contactsMetadata } from "./contacts/metadata";
export { FaqPage } from "./faq";
export { metadata as faqMetadata } from "./faq/metadata";
export { HomePage } from "./home";
export { metadata as homeMetadata } from "./home/metadata";
export { ProductPage } from "./product";
export { metadata as productMetadata } from "./product/metadata";
